# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-MultiConf
version:      0.0100_01
version_from: lib/Module/MultiConf.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Data::Inheritable:      0
    Config::Any:                   0
    Params::Validate:              0
    Scalar::Util:                  0
    Symbol:                        0
    UNIVERSAL:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
