---
abstract: 'Configure and validate your app modules in one go'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-MultiConf
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Class::Data::Inheritable: 0
  Config::Any: 0
  Params::Validate: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.0401
